version: "3.8"
services:
  web:
    build: .
    container_name: rag_web
    environment:
      - OLLAMA_HOST=http://ollama:11434
    ports:
      - "8080:5000"
    depends_on:
      - ollama
    volumes:
      - ./docs:/app/docs
      - ./chroma_db:/app/chroma_db

  ollama:
    image: ollama/ollama:latest
    container_name: rag_ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_models:/root/.ollama

volumes:
  ollama_models:
